// Copyright (c) 2026 AdvanGeneration Pty. Ltd.
// Licensed under the MIT License.
// See LICENSE.txt for license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AdvGenNoSqlServer.Core.Abstractions;
using AdvGenNoSqlServer.Core.Models;
using AdvGenNoSqlServer.Storage;

namespace AdvGenNoSqlServer.Example.ConsoleApp
{
    /// <summary>
    /// Examples demonstrating INSERT operations - inserting new documents with explicit and
    /// auto-generated IDs, handling duplicate document errors, and bulk insert operations.
    /// 
    /// This example shows:
    /// - Basic INSERT with explicit document ID
    /// - INSERT with auto-generated ID
    /// - INSERT failure when document already exists (vs UPSERT)
    /// - Bulk insert operations for efficient data loading
    /// </summary>
    public class InsertExamples
    {
        private readonly string _baseDataPath;

        public InsertExamples(string baseDataPath = "./data/insert_examples")
        {
            _baseDataPath = baseDataPath;
        }

        /// <summary>
        /// Run all INSERT examples
        /// </summary>
        public async Task RunAllExamplesAsync()
        {
            Console.WriteLine("\n╔════════════════════════════════════════════════════════════╗");
            Console.WriteLine("║  INSERT Examples                                           ║");
            Console.WriteLine("║  Insert new documents with explicit and generated IDs      ║");
            Console.WriteLine("╚════════════════════════════════════════════════════════════╝\n");

            try
            {
                // Ensure clean state
                CleanupDataDirectory();

                // Run examples
                await RunExample1_BasicInsertWithExplicitId();
                await RunExample2_InsertWithAutoGeneratedId();
                await RunExample3_InsertValidationAndDuplicates();
                await RunExample4_BulkInsert();

                Console.WriteLine("\n✅ All INSERT examples completed successfully!\n");
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"\n❌ Example failed: {ex.Message}");
                Console.WriteLine($"   StackTrace: {ex.StackTrace}");
                Console.ResetColor();
                throw;
            }
            finally
            {
                // Cleanup
                CleanupDataDirectory();
            }
        }

        /// <summary>
        /// Example 1: Basic INSERT with Explicit Document ID
        /// Demonstrates inserting documents with user-specified IDs
        /// </summary>
        private async Task RunExample1_BasicInsertWithExplicitId()
        {
            PrintExampleHeader("Example 1: Basic INSERT with Explicit Document ID");

            // Create document store with atomic update operations
            var store = new AtomicUpdateDocumentStore();

            Console.WriteLine("\n📦 Creating collection 'users'");
            await store.CreateCollectionAsync("users");

            // Insert document with explicit ID
            Console.WriteLine("\n📝 Inserting document with explicit ID 'user_001':");
            Console.WriteLine("   { name: 'John Doe', email: 'john@example.com', age: 30 }");

            var userData = new Dictionary<string, object>
            {
                ["name"] = "John Doe",
                ["email"] = "john@example.com",
                ["age"] = 30,
                ["role"] = "customer",
                ["created_at"] = DateTime.UtcNow
            };

            var insertedDoc = await store.InsertAsync("users", "user_001", userData);

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"\n   ✅ Insert successful!");
            Console.WriteLine($"   Document ID: {insertedDoc.Id}");
            Console.WriteLine($"   Version: {insertedDoc.Version}");
            Console.WriteLine($"   Created At: {insertedDoc.CreatedAt:yyyy-MM-dd HH:mm:ss}");
            Console.ResetColor();

            // Insert another document with explicit ID
            Console.WriteLine("\n📝 Inserting another document with explicit ID 'user_002':");
            Console.WriteLine("   { name: 'Jane Smith', email: 'jane@example.com', age: 28 }");

            var user2Data = new Dictionary<string, object>
            {
                ["name"] = "Jane Smith",
                ["email"] = "jane@example.com",
                ["age"] = 28,
                ["role"] = "admin",
                ["created_at"] = DateTime.UtcNow
            };

            var insertedDoc2 = await store.InsertAsync("users", "user_002", user2Data);

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"\n   ✅ Insert successful!");
            Console.WriteLine($"   Document ID: {insertedDoc2.Id}");
            Console.ResetColor();

            // Verify documents exist
            var count = await store.CountAsync("users");
            Console.WriteLine($"\n📊 Total documents in 'users' collection: {count}");

            // Retrieve and display inserted documents
            Console.WriteLine("\n📋 Retrieving inserted documents:");
            var doc1 = await store.GetAsync("users", "user_001");
            var doc2 = await store.GetAsync("users", "user_002");

            Console.WriteLine($"\n   Document 1: {doc1?.Data["name"]} ({doc1?.Data["email"]})");
            Console.WriteLine($"   Document 2: {doc2?.Data["name"]} ({doc2?.Data["email"]})");

            Console.WriteLine("\n✅ Example 1 completed!");
        }

        /// <summary>
        /// Example 2: INSERT with Auto-Generated ID
        /// Demonstrates inserting documents where IDs are automatically generated
        /// </summary>
        private async Task RunExample2_InsertWithAutoGeneratedId()
        {
            PrintExampleHeader("Example 2: INSERT with Auto-Generated ID");

            var store = new AtomicUpdateDocumentStore();

            Console.WriteLine("\n📦 Creating collection 'products'");
            await store.CreateCollectionAsync("products");

            // Insert multiple products with auto-generated GUIDs
            Console.WriteLine("\n📝 Inserting 5 products with auto-generated IDs:\n");

            var products = new[]
            {
                new { name = "Laptop Pro", category = "Electronics", price = 1299.99, stock = 50 },
                new { name = "Wireless Mouse", category = "Electronics", price = 29.99, stock = 200 },
                new { name = "USB-C Cable", category = "Accessories", price = 14.99, stock = 500 },
                new { name = "Mechanical Keyboard", category = "Electronics", price = 149.99, stock = 75 },
                new { name = "Monitor Stand", category = "Accessories", price = 49.99, stock = 120 }
            };

            var generatedIds = new List<string>();

            foreach (var product in products)
            {
                // Generate a unique ID using GUID
                var productId = $"prod_{Guid.NewGuid().ToString("N")[..8]}";
                generatedIds.Add(productId);

                var productData = new Dictionary<string, object>
                {
                    ["name"] = product.name,
                    ["category"] = product.category,
                    ["price"] = product.price,
                    ["stock"] = product.stock,
                    ["sku"] = $"SKU-{productId[^6..]}"
                };

                var insertedDoc = await store.InsertAsync("products", productId, productData);

                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine($"   ✅ {product.name}");
                Console.ResetColor();
                Console.WriteLine($"      ID: {insertedDoc.Id}");
                Console.WriteLine($"      Price: ${product.price:F2}");
                Console.WriteLine($"      SKU: {productData["sku"]}");
            }

            // Display summary
            var count = await store.CountAsync("products");
            Console.WriteLine($"\n📊 Total products inserted: {count}");

            Console.WriteLine("\n🎲 Sample of auto-generated IDs:");
            foreach (var id in generatedIds.Take(3))
            {
                Console.WriteLine($"   - {id}");
            }

            Console.WriteLine("\n✅ Example 2 completed!");
        }

        /// <summary>
        /// Example 3: INSERT Validation and Duplicate Handling
        /// Demonstrates that INSERT fails when document already exists (unlike UPSERT)
        /// </summary>
        private async Task RunExample3_InsertValidationAndDuplicates()
        {
            PrintExampleHeader("Example 3: INSERT Validation and Duplicate Handling");

            var store = new AtomicUpdateDocumentStore();

            Console.WriteLine("\n📦 Creating collection 'orders'");
            await store.CreateCollectionAsync("orders");

            // Insert initial document
            Console.WriteLine("\n📝 Inserting initial order document 'order_100':");
            var orderData = new Dictionary<string, object>
            {
                ["customer"] = "Alice Johnson",
                ["total"] = 150.00,
                ["status"] = "pending",
                ["items"] = 3
            };

            var insertedDoc = await store.InsertAsync("orders", "order_100", orderData);
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"   ✅ Insert successful! Document ID: {insertedDoc.Id}");
            Console.ResetColor();

            // Try to insert the same document again (should fail)
            Console.WriteLine("\n📝 Attempting to insert 'order_100' again (duplicate):");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine("   ⚠️ Expected: DocumentAlreadyExistsException");
            Console.ResetColor();

            try
            {
                var duplicateData = new Dictionary<string, object>
                {
                    ["customer"] = "Bob Smith",
                    ["total"] = 250.00,
                    ["status"] = "confirmed",
                    ["items"] = 5
                };

                await store.InsertAsync("orders", "order_100", duplicateData);

                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("   ❌ ERROR: Insert should have failed but succeeded!");
                Console.ResetColor();
            }
            catch (DocumentAlreadyExistsException ex)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine($"   ✅ Correctly threw DocumentAlreadyExistsException");
                Console.WriteLine($"      Message: {ex.Message}");
                Console.ResetColor();
            }

            // Show the original document is unchanged
            Console.WriteLine("\n📋 Verifying original document is unchanged:");
            var originalDoc = await store.GetAsync("orders", "order_100");
            Console.WriteLine($"   Customer: {originalDoc?.Data["customer"]}");
            Console.WriteLine($"   Total: ${originalDoc?.Data["total"]}");
            Console.WriteLine($"   Status: {originalDoc?.Data["status"]}");

            // Contrast with UPDATE behavior
            Console.WriteLine("\n📝 Using UPDATE to modify existing document:");
            var updateData = new Dictionary<string, object>
            {
                ["customer"] = "Alice Johnson",
                ["total"] = 175.00,
                ["status"] = "confirmed",
                ["items"] = 3
            };

            var updatedDoc = new Document
            {
                Id = "order_100",
                Data = updateData
            };

            await store.UpdateAsync("orders", updatedDoc);
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"   ✅ Update successful!");
            Console.ResetColor();

            var afterUpdate = await store.GetAsync("orders", "order_100");
            Console.WriteLine($"   New Total: ${afterUpdate?.Data["total"]}");
            Console.WriteLine($"   New Status: {afterUpdate?.Data["status"]}");

            Console.WriteLine("\n✅ Example 3 completed!");
        }

        /// <summary>
        /// Example 4: Bulk Insert Operations
        /// Demonstrates efficient insertion of multiple documents
        /// </summary>
        private async Task RunExample4_BulkInsert()
        {
            PrintExampleHeader("Example 4: Bulk Insert Operations");

            var store = new AtomicUpdateDocumentStore();

            Console.WriteLine("\n📦 Creating collection 'events'");
            await store.CreateCollectionAsync("events");

            // Generate 50 event documents for bulk insert
            const int eventCount = 50;
            Console.WriteLine($"\n📝 Preparing {eventCount} event documents for bulk insert...\n");

            var events = new List<(string id, Dictionary<string, object> data)>();
            var eventTypes = new[] { "login", "logout", "purchase", "view", "click", "error" };
            var users = new[] { "user_001", "user_002", "user_003", "user_004", "user_005" };
            var random = new Random(42); // Seeded for reproducibility

            for (int i = 1; i <= eventCount; i++)
            {
                var eventId = $"evt_{DateTime.UtcNow:yyyyMMdd}_{i:D5}";
                var eventType = eventTypes[random.Next(eventTypes.Length)];
                var userId = users[random.Next(users.Length)];

                var eventData = new Dictionary<string, object>
                {
                    ["event_type"] = eventType,
                    ["user_id"] = userId,
                    ["timestamp"] = DateTime.UtcNow.AddSeconds(-random.Next(3600)),
                    ["session_id"] = $"sess_{random.Next(1000, 9999)}",
                    ["payload"] = new Dictionary<string, object>
                    {
                        ["ip"] = $"192.168.1.{random.Next(2, 255)}",
                        ["user_agent"] = "Mozilla/5.0 Example Browser",
                        ["page"] = $"/page/{random.Next(1, 10)}"
                    }
                };

                events.Add((eventId, eventData));
            }

            // Perform bulk insert with timing
            Console.WriteLine("🚀 Starting bulk insert...\n");
            var startTime = DateTime.UtcNow;
            var successCount = 0;
            var failureCount = 0;

            foreach (var (id, data) in events)
            {
                try
                {
                    await store.InsertAsync("events", id, data);
                    successCount++;

                    // Show progress every 10 documents
                    if (successCount % 10 == 0)
                    {
                        Console.WriteLine($"   📊 Progress: {successCount}/{eventCount} documents inserted...");
                    }
                }
                catch (Exception ex)
                {
                    failureCount++;
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"   ❌ Failed to insert {id}: {ex.Message}");
                    Console.ResetColor();
                }
            }

            var endTime = DateTime.UtcNow;
            var duration = endTime - startTime;
            var docsPerSecond = successCount / duration.TotalSeconds;

            // Display results
            Console.WriteLine("\n📊 Bulk Insert Results:");
            Console.WriteLine($"   ✅ Successful: {successCount}");
            Console.WriteLine($"   ❌ Failed: {failureCount}");
            Console.WriteLine($"   ⏱️ Duration: {duration.TotalMilliseconds:F0} ms");
            Console.WriteLine($"   ⚡ Throughput: {docsPerSecond:F0} docs/sec");

            // Verify all documents are in the collection
            var totalCount = await store.CountAsync("events");
            Console.WriteLine($"\n📋 Total documents in collection: {totalCount}");

            // Show sample of inserted documents
            Console.WriteLine("\n📋 Sample of inserted events:");
            var sampleEvents = (await store.GetAllAsync("events")).Take(3);
            foreach (var evt in sampleEvents)
            {
                Console.WriteLine($"   - {evt.Id}: {evt.Data["event_type"]} by {evt.Data["user_id"]}");
            }

            // Show event type distribution
            Console.WriteLine("\n📊 Event Type Distribution:");
            var allEvents = await store.GetAllAsync("events");
            var distribution = allEvents
                .GroupBy(e => e.Data["event_type"].ToString())
                .Select(g => new { Type = g.Key, Count = g.Count() })
                .OrderByDescending(x => x.Count);

            foreach (var item in distribution)
            {
                var percentage = (double)item.Count / totalCount * 100;
                Console.WriteLine($"   {item.Type}: {item.Count} ({percentage:F1}%)");
            }

            Console.WriteLine("\n✅ Example 4 completed!");
        }

        #region Helper Methods

        private void PrintExampleHeader(string title)
        {
            Console.WriteLine("\n" + new string('─', 60));
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine($"  {title}");
            Console.ResetColor();
            Console.WriteLine(new string('─', 60));
        }

        private void CleanupDataDirectory()
        {
            try
            {
                if (Directory.Exists(_baseDataPath))
                {
                    Directory.Delete(_baseDataPath, true);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Warning: Could not clean up data directory: {ex.Message}");
            }
        }

        #endregion
    }
}
